name: Python Tests

on:
  push:
    branches:
      - main 
    paths:
      - '**.py' # Trigger on changes to any Python file
      - 'requirements.txt' # Trigger if requirements.txt changes
      - '!late_probabilities.png' # Exclude plot
      - '!README.md' # Do NOT trigger on changes to README.md
  pull_request:
    branches:
      - main  # Run tests on pull requests to the main branch
    paths:
      - '**.py' 
      - 'requirements.txt' 
      - '!late_probabilities.png' 
      - '!README.md' 

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v4 # Checks out your repository code

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' 

    - name: Install dependencies (if any)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
        pip install ruff # Install ruff here

    - name: Run Ruff Linter
      run: |
        ruff check . # Checks all python files for style and format

    - name: Run tests
      run: |
        pytest