name: Python Tests

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  # Run tests on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v4 # Checks out your repository code

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' 

    - name: Install dependencies (if any)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Run tests
      run: |
        pytest