name: Python Tests

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
      - 'requirements.txt'
      - '.github/workflows/**'

  pull_request:
    branches:
      - main
    paths:
      - '**/*.py'
      - 'requirements.txt'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff

      - name: Run Ruff Linter
        run: ruff check .

      - name: Run tests
        run: pytest